### PR TITLE
fix: component update for dash 0.40.0

### LINKED ISSUE #7: Latest Dash(0.40) breaks Layout component
The latest released Dash version breaks the Layout component.
The page names and routes appears undefined in the Dash app.
This can be repduced by running the examples/map_example.py

Overview of changes in Dash: https://community.plot.ly/t/dash-0-40-0-released/21338
See the note that props.children.props are no longer available directly, but must be accessed through _dashprivate_layout.

Example quick fix:

```javascript
class Layout extends Component {
    render() {
        
        const {children, banner, basepath} = this.props;
        const [frontPage, ...subPages] = Array.isArray(children)
            ? children
            : [children];
        const subPageProps = subPages.map(({props}) => {
            //Getting the props from _dashprivate_layout
            let props2 = props._dashprivate_layout.props
            if (props2 && !props2.title && props2.children) {
                return props2.children.props;
            }
            return props2;
        });
        const pages = subPages.map((page) => {
            //Getting the props from _dashprivate_layout
            let props = page.props._dashprivate_layout.props
            return (
                <Route
                    key={props.id}
                    path={`${basepath}/${props.id}`}
                    render={() => <PageWrapper>{page}</PageWrapper>}
                />
                )
        });
```

### PR DESCRIPTION
**Pull request by orjanbp**
Re-requesting pull to fix component updates for Dash 0.40.0, after last attempted fix had some oversights. 

resolves #7

### CODE REVIEW

**Comment by orjanbp** [comment]
All necessary components should now be 0.40 compatible. They're building and the Dash example presentations are running. 

The linter is not entirely happy with the solution, but I've opted to drown out its noise in this PR so we can focus on getting a fix out already -- and then refactor for a better solution later. It looks like it should work, it just could be more elegant.

**Comment by orjanbp** [comment]
Trying to update the tests to run as if the props are coming in through `_dashprivate_layout`, but for some reason the test snapshot for `<Layout>` decides to omit its children. Even though the built component works as it should in Dash.

**Comment by eivindjahren** [comment]
> Trying to update the tests to run as if the props are coming in through `_dashprivate_layout`, but for some reason the test snapshot for `<Layout>` decides to omit its children. Even though the built component works as it should in Dash.

It seems like titles are given the value `undefined`. When I start `examples/map_example.py` and go to `localhost:8050/undefined` I get the first subpage.

**Comment by orjanbp** [comment]
Could we take a moment to sit down together and figure this out @eivindjahren ? I feel like I've been staring myself a bit blind at that part.

**Review by eivindjahren — APPROVED** [review]

**Pull request merged**
